#!/bin/bash
#
# User script for submitting jobs. A wrapper for cansub,
# canfar_job_validate and condor_submit. Normally a user should
# use cansub (without the --nopost option) so that the job goes
# through the web service. This script avoids the web service and can
# submit jobs directly on the head node for testing purposes.

EXEC_NAME=$(basename $0 .${0##*.})
EXEC_VERSION=0.2.0

msg() {
    echo " >> ${EXEC_NAME}: $1"
}

die() {
    echo "ERROR ${EXEC_NAME}: $1" 1>&2
    exit 1
}

usage() {
    echo $"Usage: ${EXEC_NAME} [OPTION] JOB_FILE VM_IMAGE VM_FLAVOR
Submit a CANFAR processing job

  JOB_FILE       HTCondor job submission file
  VM_IMAGE       OpenStack VM image used to process jobs (name or ID)
  VM_FLAVOR      OpenStack VM resource flavor used to process jobs

  -h, --help                display help and exit
  -v, --version             output version information and exit
  -V, --verbose             verbose mode for debugging


Note: Prior to running this script the following OpenStack environment
variables must be set (e.g., by sourcing your openrc file):
  OS_AUTH_URL
  OS_USERNAME
  OS_PASSWORD
  OS_TENANT_NAME     (this must be the tenant that owns the image)
"
    exit
}

VERBOSE=

# Store all options
OPTS=$(getopt \
    -o hv \
    -l help \
    -l version \
    -- "$@")

eval set -- "${OPTS}"

while true; do
    case "$1" in
	-h | --help) usage ;;
	-v | --version) echo ${EXEC_VERSION}; exit ;;
	-V | --verbose) VERBOSE="--verbose" ;;
	--)  shift; break ;; # no more options
	*) break ;; # parameters
    esac
    shift
done

[[ $# -eq 3 ]] || usage

JOB_FILE=$1
VM_IMAGE=$2
VM_FLAVOR=$3

if [[ -n ${VERBOSE} ]]; then
    echo "JOB_FILE:  ${JOB_FILE}"
    echo "VM_IMAGE:  ${VM_IMAGE}"
    echo "VM_FLAVOR: ${VM_FLAVOR}"
fi

[[ -e ${JOB_FILE} ]] || die "HTCondor job submission file '${JOB_FILE}' does not exist"

# Extract executable
JOB_SCRIPT="$(grep '^[^#]*Executable\s*=' ${JOB_FILE} | cut -d= -f2 | awk '{print $1}')" \
    || die "could not search for 'Executable' in ${JOB_FILE}"

[[ -z ${JOB_SCRIPT} ]] \
    && die "could not extract 'Executable' from ${JOB_FILE}"
[[ -e ${JOB_SCRIPT} ]] \
    || die "Executable '${JOB_SCRIPT}' extracted from ${JOB_FILE} does not exist on batch"

[[ -n ${VERBOSE} ]] && msg "JOB_SCRIPT: ${JOB_SCRIPT}"

# Call cansub with --nopost simply to share the image and translate image
# and flavor names to their IDs, which is what canfar_job_validate expects.
[[ -n ${VERBOSE} ]] && msg "cansub ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS}"
VM_IMAGE_AND_FLAVOR_IDS=$(cansub ${JOB_FILE} ${VM_IMAGE} ${VM_FLAVOR} --nopost) \
    || die "failed to share image and determine image/flavor IDs"

# big string for the job
JOB=$(canfar_job_validate ${JOB_FILE} ${JOB_SCRIPT} ${VM_IMAGE_AND_FLAVOR_IDS}) || die "failed to validate job with submission file: ${JOB_FILE}"

echo "${JOB}" | condor_submit || die "failed to submit job to queue"
