#!/bin/bash

STARTDAY="2015-01-01"
TODAY="$(date +%Y-%m-%d)"
STATDIR=/mnt/stats/openstack

usage() {
    echo >&2 "usage: $(basename $0) [openstack-rc-file]"
    exit
}

openstack_compute_usage() {
    local rcfile=$1 outdir=${2:-.}
    source ${rcfile}
    if [[ -z ${OS_PROJECT_NAME} ]] || [[ -z ${OS_PASSWORD} ]]; then
	echo >&2 "bad openstack openrc file: ${rcfile}, skipping"
	return 1
    fi
    echo "  ==> Checking ${OS_PROJECT_NAME}"
    local cloud=$(echo ${OS_AUTH_URL} | sed -e 's|https://\(.*\).cloud.computecanada.ca.*|\1|')
    local usagefile=${outdir}/${cloud}/openstack_usage_${OS_PROJECT_NAME}.csv
    local daystart=${STARTDAY}
    local dayend=${STARTDAY}
    while [[ ${dayend} != ${TODAY} ]]; do
	daystart=${dayend}
	dayend=$(date +%Y-%m-%d -d "${daystart} + 1 day")
	grep -q ${dayend} ${usagefile} 2> /dev/null && continue
	echo "${OS_PROJECT_NAME}: ${daystart} -> ${dayend}"
	echo -n "${daystart}," >> ${usagefile}
	printf "%s,%s,%s,%s\n" $(
	    openstack usage show \
		--format value \
		--start ${daystart} \
		--end ${dayend}
	) >> ${usagefile}
    done
    # remove failed stat queries and reorder
    echo "day,cpuhours,diskgbhours,rammbhours,nserver" > ${usagefile}.new
    sort -k1 ${usagefile} | grep -v day | grep -v ',,,' | uniq | sed -e 's|None|0|g' >> ${usagefile}.new
    vcp -v ${usagefile}.new vos:cadcstats/processing/openstack/${cloud}/openstack_usage_${OS_PROJECT_NAME}.csv
    mv ${usagefile}.new ${usagefile}
}

openstack_compute_usage $1 ${STATDIR}
