---

- include_vars: user_vars.yaml
- include_vars: batch_vars.yaml

#*******************************************************#


- name: Create user accounts
  ansible.builtin.user:
    name: '{{ item.name }}'
    shell: /bin/bash
  with_items: '{{ batch_users }}'


- name: Setup user's authorized_keys files
  ansible.posix.authorized_key:
    user: '{{ item.name }}'
    state: present
    key: '{{ item.pub_key }}'
  with_items: '{{ batch_users }}'


- name: Copy user csv2 cli config files
  copy:
    src: 'files/csv2/'
    dest: '/home/{{ item.name }}/.csv2/'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: '0500'
  with_items: '{{ batch_users }}'


- name: Copy user example job folder
  copy:
    src: 'files/example-job/'
    dest: '/home/{{ item.name }}/example-job/'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
    mode: '0700'
  with_items: '{{ batch_users }}'
