#!/bin/bash

EXEC_NAME=$(basename $0 .${0##*.})
EXEC_VERSION=0.3.4

msg() {
    echo -e " >> ${EXEC_NAME}: $1"
}

warn() {
    echo -e " ## WARNING ${EXEC_NAME}: $1"
}

die() {
    echo -e " !! ERROR ${EXEC_NAME}: $1" 1>&2
    exit 1
}

usage() {
    echo $"Usage: ${EXEC_NAME} [cloud]
Cleanup HTCondor with OpenStack cloud
"
    exit
}

cloud=$1

source /mnt/stats/openstack/projects/${cloud/cc-}/CANFAR-openrc.sh

export PATH="/usr/local/bin:${PATH}"

# loop on VM instance names found on nova
for vm_nova_name in $(openstack server list -f value -c Name 2> /dev/null | grep ${cloud}); do
    
    # check if cloud scheduler is tracking the VM
    vm_cs_name=$(cloud_status -m | grep ${vm_nova_name} | awk '{print $2}')
    [[ -n "${vm_cs_name}" ]] && continue

    msg "cloud_scheduler lost ${vm_nova_name}"
    vm_to_delete="${vm_to_delete} ${vm_nova_name}"

    # if vm is still running condor, shutdown daemons peacefully first
    vm_worker=$(condor_status -l -attributes Name | awk '{print $3}' | sed -e 's/"//g' | grep ${vm_nova_name})
    [[ -z "${vm_worker}" ]] && continue

    condor_off -peaceful -name ${vm_worker} -startd
    # get startd and master IPs
    addr=$(condor_status ${vm_worker} -l | grep MyAddress | head -n1 | sed  -e 's/"//g')
    if  [ -n "${addr}" ]; then 
	msg "shutdown startd daemon ${startd_addr} on ${vm_nova_name}"
	condor_off -peaceful -addr ${addr} -startd
    fi
    addr=$(condor_status ${vm_worker} -l -master | grep MasterIpAddr | sed -e 's/"//g')
    if  [[ -n "${addr}" ]]; then 
	msg "shutdown master daemon ${addr} on ${vm_nova_name}"
	condor_off -peaceful -addr ${addr} -master
    fi
done

msg "terminate all instances found on nova but not on cloud scheduler"
if [ -n "${vm_to_delete}" ]; then
    msg "deleting $(echo ${vm_to_delete} | wc -w) lost VM instances from cloud scheduler"
    openstack server delete ${vm_to_delete}
fi

msg "work around cloud scheduler threaded clean-up dead-lock"
bad_vms="$(cloud_status -m | grep Retiring | awk '{print $1}')"
if [[ -n "${bad_vms}" ]]; then
    for vm_cs_id in ${bad_vms}; do
	msg "killing VM ID ${vm_cs_id} in Retiring state"
	cloud_admin -k -n ${vm_cs_id} -c ${cloud}
    done
fi

msg "clean up unclaimed VM from condor in cloud"
cloud_status -c ${cloud} -m | \
    grep Running | \
    awk -v cloud=${cloud} \
	'{printf "if [[ $(condor_status -const \47regexp(\"%s\",Machine)\47 -af State) == Unclaimed ]]; then echo \"Terminating unclaimed VM %s in cloud %s\"; cloud_admin -c %s -k -n %s;fi \n", $2, $2, cloud, cloud, $1}' | \
    bash

for vm_nova_name in $(openstack server list --status ERROR -f value -c Name 2> /dev/null); do
    msg "deleting VM instance ${vm_nova_name} in ERROR state"
    vm_cs_name=$(cloud_status -m | grep ${vm_nova_name} | awk '{print $1}')
    if [[ -n "${vm_cs_name}" ]]; then
	cloud_admin -k -n ${vm_cs_name} -c ${cloud}
    else
	openstack server delete ${vm_nova_name} 2> /dev/null
    fi
done

#msg "renabling cloud ${cloud} and releasing any hold jobs"
#cloud_admin -e ${cloud}
#condor_release -a
