
- include_vars: batch_vars.yaml

#*******************************************************#
#Copy CANFAR support scripts

- name: Copy canfar_submit script
  copy:
    src: "files/bin/canfar_submit"
    dest: /usr/bin/canfar_submit
    owner: root
    mode: '0755'

