#!/bin/bash

# script to renew a cert and move it to ~/.ssl/cadcproxy.pem before each condor job
# very much a hack to allow transitioning for  anonymous canfar

cert=$1

# use canfar_cert to find proxy
type -P canfar_cert > /dev/null && canfar_cert ${cert} && exit 0

if [[ -z ${cert} ]] || [[ ! -e ${cert} ]]; then
    echo "WARNING: no certificate for CANFAR VOSpace access" 1>&2
    exit 0
fi

mkdir -p ~/.ssl
cadc-get-cert --cert ${cert} --days-valid=${2:-15}
mv ${cert} ~/.ssl/cadcproxy.pem
