#!/bin/bash

# script to renew a cert and move it to ~/.ssl/cadcproxy.pem before each condor job
# very much a hack to allow transitioning for anonymous canfar

cert=$1

if [[ -z ${cert} ]] || [[ ! -e ${cert} ]]; then
    echo "WARNING: no certificate for CANFAR VOSpace access" 1>&2
    exit 0
fi

mkdir -p ${HOME}/.ssl
cp ${cert} ~/.ssl/cadcproxy.pem
