
---

- include_vars: batch_vars.yaml



#- name: Set a hostname
#  hostname:
#    name: "{{ new_hostname }}"


- name: Disable SElinux
  selinux:
    policy: targeted
    state: disabled

- name: Install epel7 repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present



- name: Import htcondor repo key
  rpm_key:
    state: present
    key: https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor


- name: Download htcondor repo file
  get_url:
    url: https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
    dest: /etc/yum.repos.d/htcondor-stable-rhel7.repo
    mode: '0644'



- name: Install packages
  yum:
    name:
      - git
      - gcc
      - python3
      - python3-devel
      - wget
      - python-pip
      - condor-all
    state: present

- name: install the package, force upgrade
  pip:
    name: pip
    executable: pip3
    state: latest


- name: Install openstack pip packages
  pip:
    name:
      - cryptography==2.4.2
      - cadcutils==1.1.24
    executable: pip3

      #- python-keystoneclient
      #- python-novaclient
      #- python-glanceclient


- name: Stop condor if its running
  service:
    name: condor
    state: stopped



#Copy over condor config files...
- name: Copy condor config files
  copy:
    src: "files/etc/condor/"
    dest: /etc/condor/
    owner: root
    mode: 644




#Copy over other system files


- name: Start condor
  service:
    name: condor
    enabled: yes
    state: started



- name: Disable condor poller
  command: /opt/cloudscheduler/utilities/service_disable_condor_poller
  ignore_errors: yes


- name: Download condor poller intaller
  get_url:
    url: https://csv2-canfar.heprc.uvic.ca/repo/condor_poller.tar.gz
    dest: /tmp/condor_poller.tar.gz
    mode: '0640'

- name: Extract condor poller
  command: tar -xzvf /tmp/condor_poller.tar.gz --directory /opt
  ignore_errors: yes



- name: Enable condor poller
  command: /opt/cloudscheduler/utilities/service_enable_condor_poller
  ignore_errors: yes


